language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=google_apis/armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25+, latest, cannot get more granular control than this
    # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943 for more
    # details.
    - platform-tools #latest
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - extra
    - add-on
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-52d11cd2'
    - 'google-gdk-license-.+'

  before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - chmod +x ./gradlew
  - ./gradlew build lint test assembleAndroidTest -PdisablePreDex;
  # Make gradle output info-level logging, so the tests do not timeout
  - ./gradlew connectedCheck --info -PdisablePreDex;